# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rebalancer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rebalancer.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\nCorg.matsim.contrib.drt.optimizer.rebalancing.remoteBalancing.server',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10rebalancer.proto2\x15\n\x13RebalancingStrategyBE\nCorg.matsim.contrib.drt.optimizer.rebalancing.remoteBalancing.serverb\x06proto3'
)



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_REBALANCINGSTRATEGY = _descriptor.ServiceDescriptor(
  name='RebalancingStrategy',
  full_name='RebalancingStrategy',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=20,
  serialized_end=41,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_REBALANCINGSTRATEGY)

DESCRIPTOR.services_by_name['RebalancingStrategy'] = _REBALANCINGSTRATEGY

# @@protoc_insertion_point(module_scope)
