# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drtrl/server/rebalancer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='drtrl/server/rebalancer.proto',
  package='drtrl.server',
  syntax='proto3',
  serialized_options=b'\nCorg.matsim.contrib.drt.optimizer.rebalancing.remoteBalancing.server',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1d\x64rtrl/server/rebalancer.proto\x12\x0c\x64rtrl.server\"\x07\n\x05\x45mpty\"8\n\x04Zone\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tcentroidX\x18\x02 \x01(\x01\x12\x11\n\tcentroidY\x18\x03 \x01(\x01\"b\n\x18RebalancingSpecification\x12\x10\n\x08interval\x18\x01 \x01(\x05\x12\x11\n\tfleetSize\x18\x02 \x01(\x05\x12!\n\x05zones\x18\x03 \x03(\x0b\x32\x12.drtrl.server.Zone\";\n\x0b\x43urrentTime\x12\x13\n\x0b\x63urrentTime\x18\x01 \x01(\x05\x12\x17\n\x0fsimulationEnded\x18\x02 \x01(\x08\".\n\x17RebalancingInstructions\x12\x13\n\x0b\x63urrentTime\x18\x01 \x01(\x05\"\x12\n\x10RebalancingState2\x92\x02\n\x13RebalancingStrategy\x12Q\n\x10GetSpecification\x12\x13.drtrl.server.Empty\x1a&.drtrl.server.RebalancingSpecification\"\x00\x12N\n\x0fGetCurrentState\x12\x19.drtrl.server.CurrentTime\x1a\x1e.drtrl.server.RebalancingState\"\x00\x12X\n\x12PerformRebalancing\x12%.drtrl.server.RebalancingInstructions\x1a\x19.drtrl.server.CurrentTime\"\x00\x42\x45\nCorg.matsim.contrib.drt.optimizer.rebalancing.remoteBalancing.serverb\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='drtrl.server.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=54,
)


_ZONE = _descriptor.Descriptor(
  name='Zone',
  full_name='drtrl.server.Zone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='drtrl.server.Zone.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='centroidX', full_name='drtrl.server.Zone.centroidX', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='centroidY', full_name='drtrl.server.Zone.centroidY', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=112,
)


_REBALANCINGSPECIFICATION = _descriptor.Descriptor(
  name='RebalancingSpecification',
  full_name='drtrl.server.RebalancingSpecification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='interval', full_name='drtrl.server.RebalancingSpecification.interval', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fleetSize', full_name='drtrl.server.RebalancingSpecification.fleetSize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='zones', full_name='drtrl.server.RebalancingSpecification.zones', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=212,
)


_CURRENTTIME = _descriptor.Descriptor(
  name='CurrentTime',
  full_name='drtrl.server.CurrentTime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='currentTime', full_name='drtrl.server.CurrentTime.currentTime', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='simulationEnded', full_name='drtrl.server.CurrentTime.simulationEnded', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=273,
)


_REBALANCINGINSTRUCTIONS = _descriptor.Descriptor(
  name='RebalancingInstructions',
  full_name='drtrl.server.RebalancingInstructions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='currentTime', full_name='drtrl.server.RebalancingInstructions.currentTime', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=321,
)


_REBALANCINGSTATE = _descriptor.Descriptor(
  name='RebalancingState',
  full_name='drtrl.server.RebalancingState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=341,
)

_REBALANCINGSPECIFICATION.fields_by_name['zones'].message_type = _ZONE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Zone'] = _ZONE
DESCRIPTOR.message_types_by_name['RebalancingSpecification'] = _REBALANCINGSPECIFICATION
DESCRIPTOR.message_types_by_name['CurrentTime'] = _CURRENTTIME
DESCRIPTOR.message_types_by_name['RebalancingInstructions'] = _REBALANCINGINSTRUCTIONS
DESCRIPTOR.message_types_by_name['RebalancingState'] = _REBALANCINGSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'drtrl.server.rebalancer_pb2'
  # @@protoc_insertion_point(class_scope:drtrl.server.Empty)
  })
_sym_db.RegisterMessage(Empty)

Zone = _reflection.GeneratedProtocolMessageType('Zone', (_message.Message,), {
  'DESCRIPTOR' : _ZONE,
  '__module__' : 'drtrl.server.rebalancer_pb2'
  # @@protoc_insertion_point(class_scope:drtrl.server.Zone)
  })
_sym_db.RegisterMessage(Zone)

RebalancingSpecification = _reflection.GeneratedProtocolMessageType('RebalancingSpecification', (_message.Message,), {
  'DESCRIPTOR' : _REBALANCINGSPECIFICATION,
  '__module__' : 'drtrl.server.rebalancer_pb2'
  # @@protoc_insertion_point(class_scope:drtrl.server.RebalancingSpecification)
  })
_sym_db.RegisterMessage(RebalancingSpecification)

CurrentTime = _reflection.GeneratedProtocolMessageType('CurrentTime', (_message.Message,), {
  'DESCRIPTOR' : _CURRENTTIME,
  '__module__' : 'drtrl.server.rebalancer_pb2'
  # @@protoc_insertion_point(class_scope:drtrl.server.CurrentTime)
  })
_sym_db.RegisterMessage(CurrentTime)

RebalancingInstructions = _reflection.GeneratedProtocolMessageType('RebalancingInstructions', (_message.Message,), {
  'DESCRIPTOR' : _REBALANCINGINSTRUCTIONS,
  '__module__' : 'drtrl.server.rebalancer_pb2'
  # @@protoc_insertion_point(class_scope:drtrl.server.RebalancingInstructions)
  })
_sym_db.RegisterMessage(RebalancingInstructions)

RebalancingState = _reflection.GeneratedProtocolMessageType('RebalancingState', (_message.Message,), {
  'DESCRIPTOR' : _REBALANCINGSTATE,
  '__module__' : 'drtrl.server.rebalancer_pb2'
  # @@protoc_insertion_point(class_scope:drtrl.server.RebalancingState)
  })
_sym_db.RegisterMessage(RebalancingState)


DESCRIPTOR._options = None

_REBALANCINGSTRATEGY = _descriptor.ServiceDescriptor(
  name='RebalancingStrategy',
  full_name='drtrl.server.RebalancingStrategy',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=344,
  serialized_end=618,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSpecification',
    full_name='drtrl.server.RebalancingStrategy.GetSpecification',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_REBALANCINGSPECIFICATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetCurrentState',
    full_name='drtrl.server.RebalancingStrategy.GetCurrentState',
    index=1,
    containing_service=None,
    input_type=_CURRENTTIME,
    output_type=_REBALANCINGSTATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PerformRebalancing',
    full_name='drtrl.server.RebalancingStrategy.PerformRebalancing',
    index=2,
    containing_service=None,
    input_type=_REBALANCINGINSTRUCTIONS,
    output_type=_CURRENTTIME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REBALANCINGSTRATEGY)

DESCRIPTOR.services_by_name['RebalancingStrategy'] = _REBALANCINGSTRATEGY

# @@protoc_insertion_point(module_scope)
